export const GLOBAL_TOGGLE_SIDEBAR = 'GLOBAL_TOGGLE_SIDEBAR';

export const LIBRARY_SEARCH            = 'LIBRARY_SEARCH';
export const LIBRARY_LIST              = 'LIBRARY_LIST';
export const REQUEST_LIBRARY_LIST      = 'REQUEST_LIBRARY_LIST';
export const GET_LIBRARY_LIST_FAILURE  = 'GET_LIBRARY_LIST_FAILURE';
export const ADD_LIBRARY_ACHIEVEMENTS  = 'ADD_LIBRARY_ACHIEVEMENTS';
export const UPDATE_GAME_SCREENSHOT    = 'UPDATE_GAME_SCREENSHOT';
export const UPDATE_GAME_ACHIEVEMENT   = 'UPDATE_GAME_ACHIEVEMENT';
export const UPDATE_GAME_INSTALL_STATE = 'UPDATE_GAME_INSTALL_STATE';
export const ADD_LIBRARY_NEWS          = 'ADD_LIBRARY_NEWS';

export const USER_INFO             = 'USER_INFO';
export const REQUEST_USER_INFO     = 'REQUEST_USER_INFO';
export const GET_USER_INFO_FAILURE = 'GET_USER_INFO_FAILURE';
